export * as MarginlyFactoryCompiled from '@marginly/contracts/artifacts/contracts/MarginlyFactory.sol/MarginlyFactory.json';
export * as MarginlyPoolCompiled from '@marginly/contracts/artifacts/contracts/MarginlyPool.sol/MarginlyPool.json';
export * as TestUniswapFactoryCompiled from '@marginly/contracts/artifacts/contracts/test/TestUniswapFactory.sol/TestUniswapFactory.json';
export * as TestUniswapPoolCompiled from '@marginly/contracts/artifacts/contracts/test/TestUniswapPool.sol/TestUniswapPool.json';
export * as TestERC20Compiled from '@marginly/contracts/artifacts/contracts/test/TestERC20Token.sol/TestERC20.json';
export * as MockAavePoolCompiled from '@marginly/contracts/artifacts/contracts/test/MockAavePool.sol/MockAavePool.json';
export * as MockAavePoolAddressesProviderCompiled from '@marginly/contracts/artifacts/contracts/test/MockAavePoolAddressesProvider.sol/MockAavePoolAddressesProvider.json';
export * as MockMarginlyPoolCompiled from '@marginly/contracts/artifacts/contracts/test/MockMarginlyPool.sol/MockMarginlyPool.json';
export * as MarginlyKeeperCompiled from '@marginly/contracts/artifacts/contracts/MarginlyKeeper.sol/MarginlyKeeper.json';
// export * as MockSwapRouterCompiled from '@marginly/contracts/artifacts/contracts/test/MockSwapRouter.sol/MockSwapRouter.json';
export * as MockMarginlyFactory from '@marginly/contracts/artifacts/contracts/test/MockMarginlyFactory.sol/MockMarginlyFactory.json';
export * as MarginlyPoolAdminCompiled from '../../artifacts/contracts/MarginlyPoolAdmin.sol/MarginlyPoolAdmin.json';
export * as MarginlyRouterCompiled from '@marginly/router/artifacts/contracts/MarginlyRouter.sol/MarginlyRouter.json';
export * as UniswapV3AdapterCompiled from '@marginly/router/artifacts/contracts/adapters/UniswapV3Adapter.sol/UniswapV3Adapter.json';
