name: Deploy ganache node

on:
  workflow_dispatch:

env:
  REGISTRY: trufflesuite/ganache
  IMAGE_TAG: latest
  SERVICE_NAME: ${{ secrets.SERVICE_NAME_GANACHE }}
  CLUSTER: ${{ secrets.CLUSTER }}
  NAMESPACE: ${{ secrets.NAMESPACE }}
  HELM_REPOSITORY: "ethpandaops/ethereum-helm-charts"
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.0
      - name: 'Clone Helm repository'
        uses: actions/checkout@v3
        with:
          repository: ${{ env.HELM_REPOSITORY }}
          ref: 'master'
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
            method: kubeconfig
            kubeconfig: ${{ secrets.KUBECONFIG }}
            context: ${{ env.CLUSTER }}
      - name: 'Create env file'
        run: |
          echo "${{ secrets.EXTRAENV_GANACHE }}" > extraEnv.yml
      - name: 'Deploy node'
        run: |
          helm upgrade -i $SERVICE_NAME \
          -n $NAMESPACE \
          --set fullnameOverride=$SERVICE_NAME \
          --set service.enabled=true \
          --set service.port=8545 \
          --set service.targetport=8545 \
          --set image.repository=$REGISTRY \
          --set image.tag=$IMAGE_TAG \
          -f extraEnv.yml \
          ./charts/ganache/
