name: Deploy ganache node

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}
  SERVICE_NAME: marginly-ganache-gitlab
  CLUSTER: kube
  NAMESPACE: eth-backend-test
  # IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  # GH_SECR: github-marginly
  # LIMIT_CPU: "500m"
  # LIMIT_MEMORY: "512Mi"
  HELM_REPOSITORY: "ethpandaops/ethereum-helm-charts"



    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.0
      - name: 'Clone Helm repository'
        uses: actions/checkout@v3
        with:
          repository: ${{ env.HELM_REPOSITORY }}
          ref: 'master'
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
            method: kubeconfig
            kubeconfig: ${{ secrets.KUBECONFIG }}
            context: ${{ env.CLUSTER }}
      - name: 'Create env file'
        run: |
          echo "${{ secrets.EXTRAENV_GANACHE }}" > extraEnv.yml
      - name: 'Deploy node'
        run: |
          helm upgrade -i $SERVICE_NAME \
          --set fullnameOverride=$SERVICE_NAME \
          --set service.enabled=true \
          --set service.port=8545 \
          --set service.targetport=8545 \
          -f extraEnv.yml \
          ./charts/ganache/