name: Unit tests periphery
on:
  push:
  pull_request:
  workflow_dispatch:
  paths:
    - packages/periphery
jobs:
    unit_tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 18.14.2
          uses: actions/setup-node@v3
          with:
            node-version: 18.14.2
        - name: Build for testing periphery
          run: |
            cd packages/periphery
            yarn
            yarn test
            
        
