name: Unit tests uniswap mock
on:
  push:
  pull_request:
  workflow_dispatch:
  paths:
    - packages/common
    - packages/contracts-uniswap-mock
jobs:
    unit_tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 18.14.2
          uses: actions/setup-node@v3
          with:
            node-version: 18.14.2
        - name: Build for testing uniswap mock
          run: |
            cd packages/common
            yarn
            yarn build
            cd ../contracts-uniswap-mock
            yarn
            yarn test
